version: '2'

services:
  taskdash:
    image: taskdash_20200819
    restart: always
    hostname: taskdash
    ports:
      - "8080:8080"
    networks:
      - taskdash-network
networks:
  taskdash-network:
    driver: bridge