version: '2'

services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    networks:
      - nsq-network
    hostname: nsqlookupd
    ports:
      - "4161:4161"
      - "4160:4160"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 -broadcast-address=192.168.51.12
    depends_on:
      - nsqlookupd
    hostname: nsqd
    networks:
      - nsq-network
    ports:
      - "4151:4151"
      - "4150:4150"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    hostname: nsqadmin
    ports:
      - "4171:4171"
    networks:
      - nsq-network

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    networks:
      - mongo-network
    ports:
      - "27018:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_DATABASE: task
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/wusg/mongo/data:/data/db
    command: mongod

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    links:
      - mongo:mongo
    depends_on:
      - mongo
    networks:
      - mongo-network
    ports:
      - "27019:8081"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 123456

#  taskdash:
#    image: taskdash0908
#    depends_on:
#      - nsqlookupd
#      - nsqadmin
#      - nsqd
#      - mongo
#      - mongo-express
#    restart: always
#    hostname: taskdash
#    ports:
#      - "8080:8080"
#    networks:
#      - taskdash-network
#
#  annotator:
#    image: annotator0908
#    depends_on:
#      - nsqlookupd
#      - nsqadmin
#      - nsqd
#      - mongo
#      - mongo-express
#    restart: always
#    hostname: annotator
#    ports:
#      - "8081:8081"
#    networks:
#      - annotator-network
#
#  mapdeck:
#    image: mapdeck0908
#    depends_on:
#      - nsqlookupd
#      - nsqadmin
#      - nsqd
#      - mongo
#      - mongo-express
#    restart: always
#    hostname: mapdeck
#    ports:
#      - "8090:8090"
#    networks:
#      - mapdeck-network

networks:
  nsq-network:
    driver: bridge
  mongo-network:
    driver: bridge
  taskdash-network:
    driver: bridge
  annotator-network:
    driver: bridge
  mapdeck-network:
    driver: bridge