version: '2'

services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    networks:
      - nsq-network
    hostname: nsqlookupd
    ports:
      - "4161:4161"
      - "4160:4160"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 -broadcast-address=192.168.51.12
    depends_on:
      - nsqlookupd
    hostname: nsqd
    networks:
      - nsq-network
    ports:
      - "4151:4151"
      - "4150:4150"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    hostname: nsqadmin
    ports:
      - "4171:4171"
    networks:
      - nsq-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    # command: ["--bind_ip_all"]
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    hostname: mongo-express
    ports:
      - 8081:8081
    networks:
      - mongo-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root

  taskdash:
    image: taskdash20200812
    depends_on:
      - nsqlookupd
      - nsqadmin
      - nsqd
      - mongo
      - mongo-express
    restart: always
    hostname: taskdash
    ports:
      - "8080:8080"
    networks:
      - taskdash-network

networks:
  nsq-network:
    driver: bridge
  mongo-network:
    driver: bridge
  taskdash-network:
    driver: bridge